


def import_antd_component()->str:
    return"""

        const {
            Button,
            FloatButton,
            Typography,
            Divider,
            Flex,
            Grid,
            Layout,
            Space,
            Anchor,
            Breadcrumb,
            Dropdown,
            Menu,
            Pagination,
            Steps,
            AutoComplete,
            Cascader,
            Checkbox,
            ColorPicker,
            Col,
            DatePicker,
            Form,
            Input,
            InputNumber,
            Mentions,
            Radio,
            Rate,
            Row,
            Select,
            Slider,
            Switch,
            TimePicker,
            Transfer,
            TreeSelect,
            Upload,
            Avatar,
            Badge,
            Calendar,
            Card,
            Carousel,
            Collapse,
            Descriptions,
            Empty,
            Image,
            List,
            Popover,
            QRCode,
            Segmented,
            Statistic,
            Table,
            Tabs,
            Tag,
            Timeline,
            Tooltip,
            Tour,
            Tree,
            Alert,
            Drawer,
            Message,
            Modal,
            Notification,
            Popconfirm,
            Progress,
            Result,
            Skeleton,
            Spin,
            Watermark,
            Affix,
            App,
            ConfigProvider 
        } = antd;
        const { Header, Content, Sider, Footer } = Layout;

    """
